import LawyerFixVid from './media/LawyerFixVid.mp4'
import NewCase from './media/NewCase.PNG'
import AdminDash from './media/AdminDash.PNG'
import BigDataVid from './media/BigData.mp4'
import BigDataHomePage from './media/BigDataHomePage.JPG'
import Nasa from './media/Nasa.JPG'
import RecentEvents from './media/RecentEvents.JPG'
import SunA from './media/SunA.JPG'
import SunB from './media/SunB.JPG'


export const ProjectList = [
    {
        projectName: "LawyerFix",
        Technologies: "React.js, CSS, Firebase, Material-UI (MUI)",
        // explaination: ["LawyerFix is an application designed for the efficient management of a lawyer's office, catering to the needs of three main user roles: admin (office boss), lawyers, and clients. \n Clients using the application can track the progress of their respective cases as they are being handled by their assigned lawyers. Additionally, clients have the ability to communicate with their lawyers through a chat feature.Lawyers can access a comprehensive overview of all their cases, including both expired and active cases. They can update the status of each active case, indicating the current stage or progress.The admin role in LawyerFix has access to all the cases within the office. This allows the admin to monitor and stay informed about the status of every case, providing a comprehensive overview of the office's operations. In addition to these monitoring capabilities, the admin role also has access to all the features available to the lawyers.","The application was developed using React.js as the primary framework. The Firebase Realtime Database was utilized as the backend database for storing and retrieving case-related information in real-time. CSS was used for styling the application, ensuring an appealing user interface. Material-UI (MUI) components were employed to enhance the overall design and provide a consistent and user-friendly experience throughout the application." ],
        media: [LawyerFixVid,NewCase,AdminDash],
        explaination: "LawyerFix is an application designed for the efficient management of a lawyer's office, catering to the needs of three main user roles: admin (office boss), lawyers, and clients. \n Clients using the application can track the progress of their respective cases as they are being handled by their assigned lawyers. Additionally, clients have the ability to communicate with their lawyers through a chat feature.Lawyers can access a comprehensive overview of all their cases, including both expired and active cases. They can update the status of each active case, indicating the current stage or progress.The admin role in LawyerFix has access to all the cases within the office. This allows the admin to monitor and stay informed about the status of every case, providing a comprehensive overview of the office's operations. In addition to these monitoring capabilities, the admin role also has access to all the features available to the lawyers. The application was developed using React.js as the primary framework. The Firebase Realtime Database was utilized as the backend database for storing and retrieving case-related information in real-time. CSS was used for styling the application, ensuring an appealing user interface. Material-UI (MUI) components were employed to enhance the overall design and provide a consistent and user-friendly experience throughout the application." ,
        githubLink:"https://github.com/RoiMeshulam/LawyerFixLastVersion"
    },
    {
        projectName: "FlyGift",
        Technologies: "React.js, CSS, Firebase (Realtime Database), Material-UI (MUI), Tequila API (KIWI API), EmailJS",
        // explaination: ["FlyGift is an application that provides a convenient way to search for flights and manage flight-related activities. The app incorporates various features to enhance the user experience and facilitate the gifting of flights.Users of FlyGift can search for flights using the Tequila API (also known as the KIWI API) to retrieve flight information and perform queries for airports and flights. The application allows users to accumulate points by charging them to their account. These points can be redeemed for personal flight tickets or used to send Fly Gifts to friends or multiple recipients.The FlyGift app includes a functionality to send points and invites to friends, enabling users to invite others to join the app and benefit from its features. For example, if you are an employer, you can purchase FlyGifts for all your company members, allowing them to choose their desired flight destinations." , "The technologies used in developing FlyGift include React.js as the primary framework for building the application's user interface. Firebase is utilized as the backend, specifically the Realtime Database, to store and retrieve flight-related data and user information. CSS is used to style the application, ensuring an attractive and user-friendly interface. Material-UI (MUI) components are incorporated to enhance the visual design and maintain consistency throughout the app. The Tequila API (KIWI API) is integrated into the application to facilitate airport and flight queries, providing users with up-to-date flight information. Lastly, EmailJS is employed to enable email communication within the app." ],
        explaination: "FlyGift is an application that provides a convenient way to search for flights and manage flight-related activities. The app incorporates various features to enhance the user experience and facilitate the gifting of flights.Users of FlyGift can search for flights using the Tequila API (also known as the KIWI API) to retrieve flight information and perform queries for airports and flights. The application allows users to accumulate points by charging them to their account. These points can be redeemed for personal flight tickets or used to send Fly Gifts to friends or multiple recipients.The FlyGift app includes a functionality to send points and invites to friends, enabling users to invite others to join the app and benefit from its features. For example, if you are an employer, you can purchase FlyGifts for all your company members, allowing them to choose their desired flight destinations.The technologies used in developing FlyGift include React.js as the primary framework for building the application's user interface. Firebase is utilized as the backend, specifically the Realtime Database, to store and retrieve flight-related data and user information. CSS is used to style the application, ensuring an attractive and user-friendly interface. Material-UI (MUI) components are incorporated to enhance the visual design and maintain consistency throughout the app. The Tequila API (KIWI API) is integrated into the application to facilitate airport and flight queries, providing users with up-to-date flight information. Lastly, EmailJS is employed to enable email communication within the app." ,
        media: [LawyerFixVid,NewCase,AdminDash],
        githubLink: "https://github.com/RoiMeshulam/FlyGift"
    },
    {
        projectName: "Big Databases",
        Technologies: "React, Material-UI (MUI), Node.js, ElasticSearch, Redis, Docker, Kafka",
        // explaination: ["BigDatabases is a project aimed at designing a system that aggregates and processes alerts related to astronomical events. The system provides real-time (NRT) updates as well as daily updates, storing the information and enabling research and search capabilities.The application utilizes several technologies to achieve its objectives. React is used as the frontend framework, providing a dynamic and interactive user interface. Material-UI (MUI) components are incorporated to enhance the user experience and ensure a visually appealing design.On the backend, Node.js is used to build the server-side logic and handle data processing. The application leverages ElasticSearch, a powerful search and analytics engine, to store and index the astronomical event data. This enables efficient and fast search capabilities within the application",".Redis, an in-memory data structure store, is utilized to cache frequently accessed data, optimizing performance and reducing response times. Docker is employed to containerize the application, ensuring portability and easy deployment across different environments.Kafka, a distributed event streaming platform, is integrated into the system to handle the ingestion and processing of alerts. It acts as a message broker, facilitating the communication between different components of the application.Overall, BigDatabases offers a comprehensive solution for aggregating, storing, and searching astronomical event data. The combination of React, MUI, Node.js, ElasticSearch, Redis, Docker, and Kafka ensures efficient data processing, seamless user interaction, and reliable performance."],
        explaination: "BigDatabases is a project aimed at designing a system that aggregates and processes alerts related to astronomical events. The system provides real-time (NRT) updates as well as daily updates, storing the information and enabling research and search capabilities.The application utilizes several technologies to achieve its objectives. React is used as the frontend framework, providing a dynamic and interactive user interface. Material-UI (MUI) components are incorporated to enhance the user experience and ensure a visually appealing design.On the backend, Node.js is used to build the server-side logic and handle data processing. The application leverages ElasticSearch, a powerful search and analytics engine, to store and index the astronomical event data. This enables efficient and fast search capabilities within the application.Redis, an in-memory data structure store, is utilized to cache frequently accessed data, optimizing performance and reducing response times. Docker is employed to containerize the application, ensuring portability and easy deployment across different environments.Kafka, a distributed event streaming platform, is integrated into the system to handle the ingestion and processing of alerts. It acts as a message broker, facilitating the communication between different components of the application.Overall, BigDatabases offers a comprehensive solution for aggregating, storing, and searching astronomical event data. The combination of React, MUI, Node.js, ElasticSearch, Redis, Docker, and Kafka ensures efficient data processing, seamless user interaction, and reliable performance." ,
        media: [BigDataVid,BigDataHomePage,RecentEvents,Nasa,SunA,SunB],
        githubLink:"https://github.com/RoiMeshulam/BigDatabases"
    }

    


]